AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'bedrock-rag

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: abp
        POWERTOOLS_LOG_LEVEL: INFO
Resources:
  BedrockRagCallLangchainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bedrock-rag-call-langchain
      CodeUri: BedrockRagCallLangchainFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
        - sg-0d4e2b03ef4272b9b
        SubnetIds:
        - subnet-033e6f24082cd002d
        - subnet-04ab6722e026991ce
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.BedrockRagCallLangchainFunction012d7987DepLayer
    Metadata:
      SamResourceId: BedrockRagCallLangchainFunction
  BedrockRagCallFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bedrock-rag-call
      CodeUri: BedrockRagCallFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
        - sg-0d4e2b03ef4272b9b
        SubnetIds:
        - subnet-033e6f24082cd002d
        - subnet-04ab6722e026991ce
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.BedrockRagCallFunction492bd932DepLayer
    Metadata:
      SamResourceId: BedrockRagCallFunction
  AbpKnowledgeBaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: abp-knowledge-base
      CodeUri: AbpKnowledgeBaseFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
        - sg-0d4e2b03ef4272b9b
        SubnetIds:
        - subnet-033e6f24082cd002d
        - subnet-04ab6722e026991ce
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.AbpKnowledgeBaseFunction748a3933DepLayer
    Metadata:
      SamResourceId: AbpKnowledgeBaseFunction
  ContactHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: abp-contact-history
      CodeUri: ContactHistoryFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
        - sg-0d4e2b03ef4272b9b
        SubnetIds:
        - subnet-033e6f24082cd002d
        - subnet-04ab6722e026991ce
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.ContactHistoryFunction8f134c08DepLayer
    Metadata:
      SamResourceId: ContactHistoryFunction
  LlmCallFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: llm-call
      CodeUri: LlmCallFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
        - sg-0d4e2b03ef4272b9b
        SubnetIds:
        - subnet-033e6f24082cd002d
        - subnet-04ab6722e026991ce
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.LlmCallFunctiond88f9b3aDepLayer
    Metadata:
      SamResourceId: LlmCallFunction
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/jinoos/dev/abp/lambdas/bedrock-rag-call-langchain/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  BedrockRagCallLangchainFunction:
    Description: Bedrock Rag Call Langchain Lambda Function ARN
    Value:
      Fn::GetAtt:
      - BedrockRagCallLangchainFunction
      - Arn
  BedrockRagCallFunction:
    Description: Bedrock Rag Call Lambda Function ARN
    Value:
      Fn::GetAtt:
      - BedrockRagCallFunction
      - Arn
  AbpKnowledgeBaseFunction:
    Description: Knowledge Base Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AbpKnowledgeBaseFunction
      - Arn
  ContactHistoryFunction:
    Description: Contact History Management Function ARN
    Value:
      Fn::GetAtt:
      - ContactHistoryFunction
      - Arn
  LlmCallFunction:
    Description: Contact History Management Function ARN
    Value:
      Fn::GetAtt:
      - LlmCallFunction
      - Arn
