AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test

Mappings:
  StackConfig:
    StackInfo:
      StackIdShort: !Select
        - 4
        - !Split
          - '-'
          - !Select
            - 2
            - !Split
              - '/'
              - !Ref AWS::StackId

Resources:
  TemporaryTestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "temp-test-bucket-${ImportValue:StackId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter1Day
            Status: Enabled
            ExpirationInDays: 1

Outputs:
  StackIdOutput:
    Value: !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ]
    Export:
      Name: StackId
  StackIdShortOutput:
    Value: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ]
    Export:
      Name: StackIdShort
  TemporaryBucketName:
    Description: Name of the temporary test bucket
    Value: !Ref TemporaryTestBucket
