AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda & Api Gateway of AI Agent Assistant for Bedrock with Knowledge Base

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lambda & Api Gateway Settings
        Parameters:
          - LambdaSubnets
          - LambdaSGs
      - Label:
          default: LLM Settings
        Parameters:
          - BedrockRegion
          - BedrockModelId
          - BedrockModelIdSummary
          - BedrockKnowledgeBaseId
      - Label:
          default: Semantic Cache Settings
        Parameters:
          - SemanticCacheEnable
          - SemanticCacheEmbeddingModelId
          - SemanticCacheVectorDBEndpoint

Parameters:
  LambdaSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private Subnets for Lambda Function
  LambdaSGs:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group for Lambda Function
  BedrockRegion:
    Type: String
    Description: Bedrock Region
    Default: us-west-2
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - af-south-1
      - ap-east-1
      - ap-south-2
      - ap-southeast-3
      - ap-southeast-5
      - ap-southeast-4
      - ap-south-1
      - ap-northeast-3
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - ca-west-1
      - cn-north-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-south-1
      - eu-west-3
      - eu-south-2
      - eu-north-1
      - eu-central-2
      - il-central-1
      - me-south-1
      - me-central-1
      - sa-east-1
  BedrockModelId:
    Type: String
    Description: Bedrock Model Id (see https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html)
    Default: anthropic.claude-3-haiku-20240307-v1:0
  BedrockModelIdSummary:
    Type: String
    Description: Bedrock Model Id for Call Summary
    Default: anthropic.claude-3-5-sonnet-20240620-v1:0
  BedrockKnowledgeBaseId:
    Type: String
    Description: Bedrock Knowledge Base Id
  SemanticCacheEnable:
    Type: String
    Description: Semantic Cache Enable (True/False)
    Default: False
    AllowedValues:
      - True
      - False
  SemanticCacheEmbeddingModelId:
    Type: String
    Description: Semantic Cache Embedding Model Id
    Default: amazon.titan-embed-text-v2:0
  SemanticCacheVectorDBEndpoint:
    Type: String
    Description: Semantic Cache VectorDB Endpoint (only for OpenSearch Serverless Endpoint)
    Default: " "



# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 256

Resources:
  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/lambda.template
      Parameters:
        LambdaSubnets: !Join [',', !Ref LambdaSubnets]
        LambdaSGs: !Join [',', !Ref LambdaSGs]

  ApiGw:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/apigw.template
      Parameters:
        BedrockRagCallLangchainFunctionArn: !GetAtt Lambda.Outputs.BedrockRagCallLangchainFunction
        KnowledgeBaseFunctionArn: !GetAtt Lambda.Outputs.KnowledgeBaseFunction
        LlmCallFunctionArn: !GetAtt Lambda.Outputs.LlmCallFunction
        ContactHistoryFunctionArn: !GetAtt Lambda.Outputs.ContactHistoryFunction

  DDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/ddb.template

  SSM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cfn/ssm.template
      Parameters:
        BedrockRegion: !Ref BedrockRegion
        BedrockModelId: !Ref BedrockModelId
        BedrockKnowledgeBaseId: !Ref BedrockKnowledgeBaseId
        SemanticCacheEnabled: !Ref SemanticCacheEnable
        SemanticCacheVectorDBEndpoint: !Ref SemanticCacheVectorDBEndpoint
        SemanticCacheEmbeddingModelId: !Ref SemanticCacheEmbeddingModelId
        DDBLlmHistoryTable: !GetAtt DDB.Outputs.DDBLlmHistoryTable
        DDBContactSummaryTable: !GetAtt DDB.Outputs.DDBContactSummaryTable

Outputs:
  BedrockRagCallLangchainFunction:
    Description: "Bedrock Rag Call Langchain Lambda Function ARN"
    Value: !GetAtt Lambda.Outputs.BedrockRagCallLangchainFunction
  #  BedrockRagCallFunction:
  #    Description: "Bedrock Rag Call Lambda Function ARN"
  #    Value: !GetAtt BedrockRagCallFunction.Arn
  KnowledgeBaseFunction:
    Description: "Knowledge Base Lambda Function ARN"
    Value: !GetAtt Lambda.Outputs.KnowledgeBaseFunction
  ContactHistoryFunction:
    Description: "Contact History Management Function ARN"
    Value: !GetAtt Lambda.Outputs.ContactHistoryFunction
  LlmCallFunction:
    Description: "Contact History Management Function ARN"
    Value: !GetAtt Lambda.Outputs.LlmCallFunction
