AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock-rag

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: abp
        POWERTOOLS_LOG_LEVEL: INFO

Resources:
  BedrockRagCallLangchainFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: bedrock-rag-call-langchain
      CodeUri: src/bedrock-rag-call-langchain/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
          - sg-0d4e2b03ef4272b9b
        SubnetIds:
          - subnet-033e6f24082cd002d
          - subnet-04ab6722e026991ce
  BedrockRagCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: bedrock-rag-call
      CodeUri: src/bedrock-rag-call/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
          - sg-0d4e2b03ef4272b9b
        SubnetIds:
          - subnet-033e6f24082cd002d
          - subnet-04ab6722e026991ce
  AbpKnowledgeBaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: abp-knowledge-base
      CodeUri: src/knowledgebase/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
          - sg-0d4e2b03ef4272b9b
        SubnetIds:
          - subnet-033e6f24082cd002d
          - subnet-04ab6722e026991ce
  ContactHistoryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: abp-contact-history
      CodeUri: src/contact-history/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
          - sg-0d4e2b03ef4272b9b
        SubnetIds:
          - subnet-033e6f24082cd002d
          - subnet-04ab6722e026991ce
  LlmCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: llm-call
      CodeUri: src/llm-call/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Role: arn:aws:iam::730335322279:role/AnyTel-Lambda
      VpcConfig:
        SecurityGroupIds:
          - sg-0d4e2b03ef4272b9b
        SubnetIds:
          - subnet-033e6f24082cd002d
          - subnet-04ab6722e026991ce

Outputs:
  BedrockRagCallLangchainFunction:
    Description: "Bedrock Rag Call Langchain Lambda Function ARN"
    Value: !GetAtt BedrockRagCallLangchainFunction.Arn
  BedrockRagCallFunction:
    Description: "Bedrock Rag Call Lambda Function ARN"
    Value: !GetAtt BedrockRagCallFunction.Arn
  AbpKnowledgeBaseFunction:
    Description: "Knowledge Base Lambda Function ARN"
    Value: !GetAtt AbpKnowledgeBaseFunction.Arn
  ContactHistoryFunction:
    Description: "Contact History Management Function ARN"
    Value: !GetAtt ContactHistoryFunction.Arn
  LlmCallFunction:
    Description: "Contact History Management Function ARN"
    Value: !GetAtt LlmCallFunction.Arn
