AWSTemplateFormatVersion: "2010-09-09"
Description:
  Stacks for UI

Resources:
# ------------------------------------------------------------#
#  S3 Bucket
# ------------------------------------------------------------#
  Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join
        - '-'
        - - 'aaa-ui'
          - !Select [2, !Split ['/', !Ref AWS::StackId]]
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: Project
          Value: AiAgentAssistant

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action: "s3:GetObject"
          Sid: AllowCloudFrontServicePrincipalReadOnly
          Effect: Allow
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            StringEquals:
              AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

# ------------------------------------------------------------#
#  CloudFront
# ------------------------------------------------------------#
  CloudFrontOriginAccessControl:
    Type: 'AWS::CloudFront::OriginAccessControl'
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "OAC-${AWS::StackName}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt Bucket.RegionalDomainName
          Id: !Sub "S3origin-${Bucket}"
          OriginAccessControlId: !Ref CloudFrontOriginAccessControl
          S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3origin-${Bucket}"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        HttpVersion: http2
        Enabled: true
      Tags:
        - Key: Project
          Value: AiAgentAssistant

Outputs:
  DistributionDomainName:
    Description: "Domain name of the CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
  Bucket:
    Description: "Bucket Name"
    Value: !Ref Bucket